version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgres://postgres:postgres@todo_db:5432/postgres
    depends_on:
      - todo_db

  todo_db:
    container_name: todo_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '80:80'
    depends_on:
      - backend
      - todo_db
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  pgdata: {}