###
POST http://localhost:4000/api/v1/create
Content-Type: application/json

{
  "todo": "test"
}

###
GET http://localhost:4000/api/v1/todos

###
PATCH http://localhost:4000/api/v1/update
Content-Type:  application/json

{
    "id" : "test",
    "isFinished": "true"
}

###
DELETE http://localhost:4000/api/v1/delete
Content-Type: application/json

{
    "todo" : "test"
}

