name: Run HTTP Requests

on: [push]

jobs:
  run-http-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Install HTTPie
        run: |
          sudo apt-get update
          sudo apt-get install -y httpie

      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo service postgresql start
          sudo -u postgres psql -c "CREATE DATABASE todo_db;"
          sudo -u postgres psql -c "CREATE USER ${{secrets.USER_NAME}} WITH PASSWORD '${{secrets.PASSWORD}}';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE todo_db TO guest;"

      - name: Run Flask
        env:
          USER_NAME: ${{secrets.USER_NAME}}
          PASSWORD: ${{secrets.PASSWORD}}
        run: |
          cd backend
          export FLASK_APP=app
          export FLASK_ENV=development
          export USER_NAME=${{secrets.USER_NAME}}
          export PASSWORD=g${{secrets.PASSWORD}}
          python3 init_db.py
          nohup flask run --host=0.0.0.0 --port=5000 & 
          sleep 5

      - name: Run HTTP Tests
        run: |
          http --ignore-stdin POST http://127.0.0.1:5000/api/v1/create \
            Content-Type:application/json \
            todo="test"

          http GET http://127.0.0.1:5000/api/v1/todos

          http --ignore-stdin PATCH http://127.0.0.1:5000/api/v1/update \
            Content-Type:application/json \
            todo="test" \
            isFinished=true

          http --ignore-stdin DELETE http://127.0.0.1:5000/api/v1/delete \
            Content-Type:application/json \
            todo="test"
