name: Run HTTP Requests

on: [push]

jobs:
  run-http-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install HTTPie
        run: |
          sudo apt-get update
          sudo apt-get install -y httpie

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Set up PostgreSQL
        uses: ./backend
        with:
          username: guest
          password: guest-password
          database: todo_db
          port: 5432
          ssl: true

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Flask && HTTP requests
        run: |
          cd backend
          export FLASK_APP=app
          export FLASK_ENV=development
          export USER_NAME=guest
          export PASSWORD=guest-password
          nohup flask run --host=0.0.0.0 --port=5000 & 
          sleep 5 
          http --ignore-stdin POST http://127.0.0.1:5000/api/v1/create \
            Content-Type:application/json \
            todo="test"

          http GET http://127.0.0.1:5000/api/v1/todos

          http PATCH http://127.0.0.1:5000/api/v1/update \
            Content-Type:application/json \
            id:=9 \
            isFinished=true

          http DELETE http://127.0.0.1:5000/api/v1/delete \
            Content-Type:application/json \
            id:=10  # Only sending id for deletion
